# Generated by Django 2.2.6 on 2021-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='address_blockchain',
            field=models.CharField(blank=True, default=' ', max_length=64),
        ),
    ]
