# Generated by Django 2.2.6 on 2020-10-13 02:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0006_auto_20201009_0352'),
        ('user', '0002_userextension_cuenta_blockchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(choices=[('T', 'Titulo'), ('N', 'Notas'), ('A', 'Acta')], max_length=1)),
                ('tipo_documento', models.CharField(choices=[('L', 'Legalizado'), ('C', 'Certificado')], max_length=1)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserExtension')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
