# Generated by Django 2.2.6 on 2021-01-18 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=70)),
                ('estado', models.CharField(choices=[('F-AC', 'Firmado AC'), ('F-C1', 'Firmado C1'), ('F-C2', 'Firmado C2'), ('C', 'Cancelado')], default='F-AC', max_length=4)),
                ('categoria', models.CharField(choices=[('T', 'Titulo'), ('N', 'Notas'), ('A', 'Acta')], max_length=1)),
                ('tipo_documento', models.CharField(choices=[('L', 'Legalizado'), ('C', 'Certificado')], max_length=1)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('archivo', models.FileField(default='documentos/default.pdf', upload_to='documentos/')),
                ('address_blockchain', models.CharField(default=' ', max_length=64)),
                ('add_dependencia', models.BooleanField(blank=True, default=False, null=True)),
                ('is_validated', models.BooleanField(blank=True, default=False, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserExtension')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
