# Generated by Django 2.2.6 on 2021-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='address_blockchain',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='is_validated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
