# Generated by Django 2.2.6 on 2021-01-06 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('R', 'Realizada'), ('P-UR', 'Procesada Unidad de Receptoria'), ('P-UA', 'Procesada Unidad de Archivo'), ('P-UP', 'Procesada Unidad de Procesamiento'), ('T', 'Concluida'), ('C', 'Cancelada')], default='R', max_length=4)),
                ('tipo', models.CharField(choices=[('L', 'Legalizados'), ('C', 'Certificados')], max_length=1)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('facultad_nucleo', models.CharField(choices=[('FAD', 'Facultad de Arquitectura y Diseño'), ('FA', 'Facultad de Arte'), ('FC', 'Facultad de Ciencias'), ('FCES', 'Facultad de Ciencias Económicas y Sociales'), ('FCFA', 'Facultad de Ciencias Forestales y Ambientales'), ('FCJP', 'Facultad de Ciencias Jurídicas y Políticas'), ('FFB', 'Facultad de Farmacia y Bioanálisis'), ('FH', 'Facultad de Humanidades y Educación'), ('FI', 'Facultad de Ingeniería'), ('FM', 'Facultad de Medicina'), ('FO', 'Facultad de Odontología'), ('NURR', 'Núcleo Universitario Rafael Rangel - Trujillo'), ('NUPR', 'Núcleo Universitario Pedro Rincon Gutierrez - Tachira'), ('NUVM', 'Núcleo Universitario Valle del Mocotíes - Tovar'), ('NUAA', 'Núcleo Universitario Alberto Adriani - El Vigia')], max_length=4)),
                ('escuela', models.CharField(max_length=50)),
                ('titulo_obtenido', models.CharField(max_length=50)),
                ('fecha_grado', models.DateField()),
                ('titulo', models.BooleanField(default=False)),
                ('notas', models.BooleanField(default=False)),
                ('acta', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserExtension')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
